## hexadecimal, regex, and blank values must have double quotes
## 
## Format: 
## 'full flag name: [value]...'
 
## name or path of volatility script 
_vol-name: /usr/local/bin/vol.py

## concurrent plugins to run
_threads: 4

## only one profile allowed
profile: WinXPSP2x86

## speeds up processing; leave blank if unsure
#kdbg: "0x0"
#dtb: "0x0"

## dump folders; subfolders will be replicated in output folder
_subfolders: base installed removed

## parent folder of mem dump(s)
_memdumps: /home/bruce/temp/paravol/wd/data/vbox

## add more information to output
#verbose: 

## parent folder for plugin output (ends up as --output-file with
## the path including the concatenation of thie path and _subfolders);
## comment out if STDOUT desired
_output_folder: /home/bruce/temp/paravol/wd/data/vol

## useful for referencing globally; default leave blank
_proc-pid: &pid "1352"

# plugin name followed by plugin specific flags/values
# 
# Format:
# <TAB> - plugin: [plugin name]
#         pluginflag: [value]...
#         pluginflag: ""
# 
plugins:
  - plugin: amcache
    hive-offset: "0x401000"

  - plugin: apihooks
    offset: "0x401000"
    pid: *pid
    name: pname
    fix: 
    quick: 
    no-whitelist: 
    skip-kernel: 
    skip-process: 

  - plugin: atoms

  - plugin: atomscan
    virtual: 
    show-unallocated: 
    start-address: "0x100"
    length: "0x100"
    offset: "0x1000"

  - plugin: bioskbd

  - plugin: cachedump
    sys-offset: value
    sec-offset: value

  - plugin: callbacks

  - plugin: cmdscan
    max-history: "50"

  - plugin: connections
    physical-offset: 

  - plugin: consoles
    history-buffers: "4"

  - plugin: dlldump
    dump-dir: path/to/dump
    regex: "[Rr]egex"
    ignore-case: 
    base: "0x0000"

  - plugin: drivermodule
    addr: "0x000"

  - plugin: dumpcerts
    ssl: 
    physical: 

  - plugin: dumpfiles
    physoffset: "1234"
    summary-file: filename
    unsafe: 
    filter: val1,val2,val3

  - plugin: dumpregistry
    hive-offset: "0x1234"

  - plugin: envars
    silent: 

  - plugin: handles
    object-type: type1,type2,type3

  - plugin: hashdump
    sam-offset: "0x101010"

  - plugin: imagecopy
    blocksize: "52500"
    output-image: imageName
    count: 

  - plugin: impscan
    size: "54321"

  - plugin: joblinks
    physical-offset: 

  - plugin: lsadump
    sec-offset: "0x010101"

  - plugin: malfind
    max-size: "12345"
    refined: 
  
  - plugin: mbrparser
    hex: 
    hash: 6acc9fad5481
    fullhash: 6aac9fad
    disoffset: "12345"
    nocheck: 
    disk: string
    maxdistance: "12345"
    zerostart: 

  - plugin: mftparser
    nocheck: 
    machine: machineName
    debugout: 

  - plugin: moddump
    unsafe: 
    memory: 

  - plugin: modscan
    virtual: 

  - plugin: mutantscan
    silent: 

  - plugin: poolpeek
    tag: tag
    min-size: "01234"
    paged: 

  - plugin: printkey
    key: reg/key

  - plugin: psxview
    apply-rules: 

  - plugin: raw2dmp
    output-image: imageName

  - plugin: strings
    string-file: filename
    scan: 
    lookup-pid: 
   
  - plugin: threads
    listtags: 
    
  - plugin: timeliner
    hive: hive
    user: username
    type: t1,t2,t3
    
  - plugin: timers
    listhead: "0x8383"
    
  - plugin: userhandles
    free: 
    
  - plugin: yarascan
    all: 
    case: 
    kernel: 
    wide: 
    yara-rules: a string
    yara-file: filename
    reverse: "01234"
    
