---
threads: 3
profile: Win10x64_17134
states: base installed removed
memdumps: /home/bruce/temp/paravol/wd/data/vbox
output: /home/bruce/temp/paravol/wd/data/vol
proc_pid: &pid 8192
plugins:
  - name: pslist
    pid: *pid
    address: 0x401303C

  - name: memdump
    pid: *pid

  - name: psxview
    


